version: "3.9"
services: 

  postgres_nsfeeds:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "admin"
    networks:
      - nfeeds
    ports:
      - '5400:5432'
      
networks:
  nfeeds: {}
